spring.application.name=ProductManager

# Perfil de configurações
spring.profiles.active=dev

# Actuator Health Check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always